project:
  type: website
  output-dir: .

website:
  title: "portfolio-mpt Documentation"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorial"
        href: tutorial.qmd
      - text: "API Reference"
        href: api.qmd

format:
  html:
    theme: cosmo
    toc: true
